config/routes.rb
Shouter::Application.routes.draw do
  root to: "homes#show", via: :get

  resource :dashboard, only: [:show]
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:index, :new, :create, :show] do
    post 'follow' => 'following_relationships#create'
    delete 'follow' => 'following_relationships#destroy'
  end
  resources :shouts, only: [:show]
  resources :text_shouts, only: [:create]
  resources :photo_shouts, only: [:create]
end

app/models/concerns/following.rb
module Concerns
  module Following
    extend ActiveSupport::Concern

    included do
      has_many :followed_user_relationships, 
                foreign_key: :follower_id,
                class_name: 'FollowingRelationship'
      has_many :followed_users, through: :followed_user_relationships

      has_many :follower_relationships, 
                foreign_key: :followed_user_id,
                class_name: 'FollowingRelationship'
      has_many :followers, through: :follower_relationships
    end

    def following? user
      followed_user_ids.include? user.id
    end

    def follow user
      followed_users << user
    end

    def unfollow user
      followed_users.delete user
    end
  end
end

app/models/dashboard.rb
class Dashboard
  def initialize user
    @user = user
  end

  def new_text_shout
    TextShout.new
  end

  def new_photo_shout
    PhotoShout.new
  end
  
  def timeline
    Timeline.new(@user)
  end
end

app/models/following_relationship.rb
class FollowingRelationship < ActiveRecord::Base
  belongs_to :follower, class_name: 'User'
  belongs_to :followed_user, class_name: 'User'
  # attr_accessible :title, :body
end

app/models/photo_shout.rb
class PhotoShout < ActiveRecord::Base
  has_attached_file :image, styles: {
    shout: '300x300>'
  }
end

app/models/shout.rb
class Shout < ActiveRecord::Base
  belongs_to :user
  default_scope { order("created_at DESC")}

  belongs_to :content, polymorphic: true

  validates_associated :content
end

app/models/text_shout.rb
class TextShout < ActiveRecord::Base
  validates :body, presence: true, length: {maximum: 140}
end

app/models/timeline.rb
class Timeline
  extend ActiveModel::Naming

  def initialize user
    @user = user
  end

  def shouts
    Shout.where(user_id: shout_user_ids)
  end


  private

  def shout_user_ids
    [@user.id] + @user.followed_user_ids
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :shouts  

  include Concerns::Following
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Monban::ControllerHelpers
  protect_from_forgery

  before_filter :create_shout

  private
  def create_shout
    @text_shout = TextShout.new
    @photo_shout = PhotoShout.new
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_filter :authenticate

  def show
    @dashboard = Dashboard.new(current_user)   
  end

  private

  def authenticate
    redirect_to new_session_path unless signed_in?
  end
end

app/controllers/following_relationships_controller.rb
class FollowingRelationshipsController < ApplicationController

  def create
    current_user.follow user
    redirect_to user, notice: 'Now following user'
  end

  def destroy
    current_user.unfollow user
    redirect_to user, notice: 'No longer following user'
  end

  private

  def user
    @_user ||= User.find(params[:user_id])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_filter :check_logged_in_user
  def show
  end

  private 

  def check_logged_in_user
    if signed_in?
      redirect_to dashboard_path
    end
  end
end

app/controllers/photo_shouts_controller.rb
class PhotoShoutsController < ApplicationController

  def create
    content = build_content
    shout = current_user.shouts.build(content: content)
    flash.alert = "Could not shout" unless shout.save
    redirect_to dashboard_path
  end

  private
  def build_content
    PhotoShout.new(photo_shout_parameters)
  end

  def photo_shout_parameters
    params.require(:photo_shout).permit(:image)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  respond_to :html

  def new
  end

  def create
    user = authenticate_session(session_params)
    sign_in(user) or set_flash_message
    respond_with user, location: root_path
  end

  def destroy
    sign_out
    redirect_to root_path
  end

  private

  def set_flash_message
    flash.now.notice = "Invalid username or password"
  end

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/shouts_controller.rb
class ShoutsController < ApplicationController
  def show
    @shout = Shout.find(params[:id])
  end
end

app/controllers/text_shouts_controller.rb
class TextShoutsController < ApplicationController

  def create
    content = build_content
    shout = current_user.shouts.build(content: content)
    flash.alert = "Could not shout" unless shout.save
    redirect_to dashboard_path
  end

  private
  def build_content
    TextShout.new(text_shout_parameters)
  end

  def text_shout_parameters
    params.require(:text_shout).permit(:body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  respond_to :html

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @shouts = @user.shouts
  end
  
  def new
    @user = User.new
  end

  def create
    @user = sign_up(user_params)
    sign_in(@user)
    respond_with @user, location: root_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shouts_helper.rb
require 'digest/md5'
module ShoutsHelper 

  def gravatar user, size = 58
    digest = Digest::MD5.hexdigest(user.email)
    image_tag("http://gravatar.com/avatar/#{digest}?s=#{size}")
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def follow_button user
    if current_user.following? user
      button_to 'Unfollow', user_follow_path(user), method: :delete
    elsif current_user != user
      button_to 'Follow', user_follow_path(user)
    end
  end
end

app/views/dashboards/show.html.erb
<%= render 'shouts/new' %>
<div class="shouts">
  <%= render @dashboard.timeline %>
</div>

app/views/homes/show.html.erb
welcome to shouter

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shouter</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="wrapper">
    <header>
      <div class="center">
        <%= link_to "Shouter", root_path, class:"logo" %>
        <nav>
          <ul>
            <% if signed_in? %>
              <li><%= link_to current_user.username, current_user, class:"username" %>|</li>
              <li><%= link_to 'Sign out', session_path, method: :delete  %>|</li>
            <% else %>
              <li><%= link_to 'Sign in', new_session_path %>|</li>
              <li><%= link_to 'Sign up', new_user_path %>|</li>
            <% end %>
            <li><%= link_to 'Users', users_path %></li>
          </ul>
        </nav>
      </div>
    </header>
    <div class="container">
      <% if alert %>
        <p class="alert"><%= alert %></p>
      <% end %>
      <% if notice %>
        <p class="notice"><%= notice %></p>
      <% end %>
      <%= yield %>
    </div>

  </div>
</body>
</html>

app/views/photo_shouts/_photo_shout.html.erb
<%= link_to(
          image_tag(photo_shout.image.url(:shout)), 
          photo_shout.image.url) %>

app/views/shouts/_new.html.erb
<h3>Shout here</h3>
<div class="forms">
  <div class="text_shout_form">
    <%= form_for @dashboard.new_text_shout do |form| %>
      <%= form.text_field :body, 
                          placeholder: 'Shout content here', 
                          class: "input"%>
      <%= form.submit 'Shout!', class: "btn1 btn-mini" %>
    <% end %>
  </div>
  <div class="photo_shout_form">
    <%= form_for @dashboard.new_photo_shout do |form| %>
      <%= form.file_field :image, class: "input"%>
      <%= form.submit 'Shout!', class: "btn1 btn-mini" %>
    <% end %>
  </div>
</div>

app/views/shouts/_shout.html.erb
<%= div_for shout do %>
  <div class="avatar">
    <%= link_to gravatar(shout.user), shout.user %>
  </div>
  <div class="content">
    <%= link_to shout.user.username, shout.user, class: "username" %>
    <span class="email"><%= shout.user.email %></span>
    <%= link_to "#{time_ago_in_words(shout.created_at)} ago.", 
                shout, class: "time" %>
    <div>
      <%= render shout.content %>
    </div>
  </div>
  <div class="comment_form">
    <form action="">
      <input type="text" placeholder="Write comment here", class="input", size="35">
      <input type="submit" value="Comment!" class="btn1 btn-mini">
    </form>
  </div>
<% end %>

app/views/shouts/show.html.erb
<%= render @shout %>

app/views/text_shouts/_text_shout.html.erb
<%= text_shout.body %>

app/views/timelines/_timeline.html.erb
<div class="timeline">
  <%= render timeline.shouts %>
</div>

app/views/users/index.html.erb
<% @users.each do |user| %>
  <div><%= link_to user.username, user %></div>
<% end %>

app/views/users/new.html.erb
<div class="signup">
  <h1>Sign up!</h1>
  <%= form_for @user do |form| %>
    <div class="fields">
      <%= form.label :username %> <br>
      <%= form.text_field :username, class: "input" %>
    </div>
    <div class="fields">
      <%= form.label :email %><br>
      <%= form.email_field :email, class: "input" %>
    </div>
    <div class="fields">
      <%= form.label :password %><br>
      <%= form.password_field :password , class: "input"%>
    </div>
    <div class="actions">
      <%= form.submit "Sign up", class: "btn1 btn-mini" %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>
<%= follow_button @user %>
<%= render @shouts %>